-- @fresh
-- Power-on with a blank save: title picture, menu without Continue, options, logbook, back.
T.run(function()
  T.wait(30)
  T.press(T.K.A); T.wait(4)
  T.check_eq(T.screen(), T.SCREEN.SPLASH, "title picture after the language pick")
  T.shot("splash")
  T.press(T.K.START); T.wait(4)
  T.check_eq(T.screen(), T.SCREEN.TITLE, "menu after the title picture")
  T.check_eq(T.menu_cursor(), T.MENU.NEW, "no run to continue: cursor on New descent")
  T.shot("title")
  T.press(T.K.LEFT)
  T.check_eq(T.menu_cursor(), T.MENU.OPTIONS, "LEFT skips the disabled Continue and wraps to Options")
  T.press(T.K.A); T.wait(4)
  T.check_eq(T.screen(), T.SCREEN.OPTIONS, "A opens the options")
  local sound_before = T.profile().sound
  T.press(T.K.A); T.wait(4)
  T.check_eq(T.profile().sound, 1 - sound_before, "A toggles the sound and saves it")
  T.press(T.K.A); T.wait(4)
  T.check_eq(T.profile().sound, sound_before, "toggled back")
  T.press(T.K.DOWN); T.press(T.K.RIGHT); T.wait(4)
  T.check_eq(T.profile().lang, 1, "RIGHT on the language row switches to English and saves it")
  T.shot("options")
  T.press(T.K.LEFT); T.wait(4)
  T.check_eq(T.profile().lang, 0, "and back to French")
  T.press(T.K.B); T.wait(4)
  T.check_eq(T.screen(), T.SCREEN.TITLE, "B leaves the options")
  T.press(T.K.UP); T.press(T.K.UP)
  T.check_eq(T.menu_cursor(), T.MENU.RECORDS, "UP twice reaches the logbook")
  T.press(T.K.A); T.wait(4)
  T.check_eq(T.screen(), T.SCREEN.RECORDS, "A opens the logbook")
  T.shot("records")
  T.press(T.K.B); T.wait(4)
  T.check_eq(T.screen(), T.SCREEN.TITLE, "B returns to the title")
end)
