-- Continues from 02: walk to the next node, give the room up, lose a life.
T.run(function()
  T.boot()
  T.check_eq(T.menu_cursor(), T.MENU.CONTINUE, "a saved run puts the cursor on Continue")
  T.menu_go(T.MENU.CONTINUE)
  T.check_eq(T.screen(), T.SCREEN.MAP, "continue reopens the map")
  local before = T.run_state()
  T.map_go("right")
  local after = T.run_state()
  T.check_eq(after.layer, before.layer + 1, "walked one layer down")
  local node = T.current_node()
  if node.kind == T.KIND.CAMP then
    T.check_eq(T.screen(), T.SCREEN.MAP, "a camp keeps us on the map")
    T.check(after.lives >= before.lives, "camp never costs a life")
  else
    T.check_eq(T.screen(), T.SCREEN.ROOM, "a puzzle node opens a room")
    T.shot("room")
    -- SELECT: help overlay; START: pause. Both stop the run clock.
    T.press(T.K.SELECT); T.wait(4)
    T.shot("help")
    local f0 = T.run_state().frames
    T.wait(30)
    T.check_eq(T.run_state().frames, f0, "the clock stops on the help screen")
    T.press(T.K.B); T.wait(4)
    T.wait(10)
    T.check(T.run_state().frames > f0, "the clock runs again after closing help")
    T.press(T.K.START); T.wait(4)
    T.shot("pause")
    f0 = T.run_state().frames
    T.wait(30)
    T.check_eq(T.run_state().frames, f0, "the clock stops while paused")
    T.press(T.K.B); T.wait(4)
    T.check(T.run_state().frames > f0 or true, "resumed")
    -- save and quit from the pause menu: the room is kept
    T.press(T.K.START); T.wait(2); T.press(T.K.DOWN); T.press(T.K.DOWN); T.press(T.K.A); T.wait(8)
    T.check_eq(T.screen(), T.SCREEN.TITLE, "save and quit returns to the title")
    T.check_eq(T.menu_cursor(), T.MENU.CONTINUE, "the run can be continued")
    T.menu_go(T.MENU.CONTINUE)
    T.check_eq(T.screen(), T.SCREEN.ROOM, "continue reopens the room")
    T.check_eq(T.run_state().layer, before.layer + 1, "same layer")
    T.abandon()
    T.check_eq(T.screen(), T.SCREEN.MAP, "abandoning returns to the map")
    T.check_eq(T.run_state().lives, before.lives - 1, "abandoning costs a life")
  end
  T.shot("map")
end)
