#!/usr/bin/env python3
"""Binary file -> C array (const, 4-byte aligned) + header with its length.

usage: bin2c.py file.bin -o outbase --name symbol
"""
import argparse
import os
import sys


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("input")
    ap.add_argument("-o", "--out", required=True, help="output base path (no extension)")
    ap.add_argument("--name", help="C symbol (default: derived from the output name)")
    a = ap.parse_args()

    data = open(a.input, "rb").read()
    name = a.name or os.path.basename(a.out)
    guard = f"{name.upper()}_H"
    with open(a.out + ".h", "w") as f:
        f.write(f"// Generated by bin2c.py from {os.path.basename(a.input)} -- do not edit\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(f"#define {name}_len {len(data)}\n")
        f.write(f"extern const unsigned char {name}[{len(data)}];\n\n#endif\n")
    with open(a.out + ".c", "w") as f:
        f.write(f"// Generated by bin2c.py from {os.path.basename(a.input)} -- do not edit\n")
        f.write(f"const unsigned char {name}[{len(data)}] __attribute__((aligned(4))) = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ",".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
