#!/usr/bin/env python3
"""Turn the core's picture drawings into a C header for the puzzle generator.

usage: heart_pictures.py assets/heart -o build/gen/heart_pictures.h

Every PNG in the folder is one picture: square, 10, 12 or 15 pixels a side,
any mode. A pixel is ore when it is opaque and dark (luminance < 128), so a
black-on-white or black-on-transparent drawing both work. The file name (minus
the extension) is the picture's name in the generator's messages.
"""
import argparse
import os
import sys
from PIL import Image

SIZES = (10, 12, 15)


def rows_of(path):
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    if w != h or w not in SIZES:
        raise SystemExit(f"{path}: pictures must be square, {'/'.join(map(str, SIZES))} px a side (got {w}x{h})")
    px = img.load()
    rows = []
    for y in range(h):
        row = ""
        for x in range(w):
            r, g, b, a = px[x, y]
            lum = (r * 299 + g * 587 + b * 114) // 1000
            row += "#" if (a >= 128 and lum < 128) else "."
        rows.append(row)
    return w, rows


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("folder")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()
    files = sorted(f for f in os.listdir(a.folder) if f.lower().endswith(".png"))
    pictures = [(os.path.splitext(f)[0],) + rows_of(os.path.join(a.folder, f)) for f in files]
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w", newline="\n") as f:
        f.write("// Generated by heart_pictures.py from assets/heart/*.png -- do not edit\n")
        f.write("#ifndef HEART_PICTURES_H\n#define HEART_PICTURES_H\n\n")
        f.write("typedef struct { const char *name; int n; const char *rows[15]; } HeartPicture;\n\n")
        f.write(f"#define HEART_PICTURE_COUNT {max(1, len(pictures))}\n\n")
        f.write("static const HeartPicture heart_pictures[HEART_PICTURE_COUNT] = {\n")
        for name, n, rows in pictures:
            f.write(f'    {{ "{name}", {n}, {{\n')
            for row in rows:
                f.write(f'        "{row}",\n')
            f.write("    } },\n")
        if not pictures:
            f.write('    { "none", 0, { 0 } },\n')
        f.write("};\n\n#endif\n")
    print(f"{len(pictures)} picture(s) -> {os.path.normpath(a.out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
