#!/usr/bin/env python3
"""Draw the placeholder source PNGs used by the game (font, grid cells,
marks, cursor, dwarf sprite).

The pixel art is defined here as ASCII art or drawn with a few PIL
primitives so it is versioned as text and can be tweaked easily. Run once to
(re)generate assets/*.png; png2gba.py turns those PNGs into GBA tile data at
build time. Final hand-drawn art replaces the PNGs with the same names and
layouts (see docs/assets.md) without touching the code.

Every image is written as an indexed (mode "P") PNG whose palette indices are
what the game expects; the real colours are chosen at run time by palette
bank, so the PNG palette is only a preview.
"""
import os
import sys
from PIL import Image

ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets")

# Glyph order in font.png; the C side (render.c FONT_CHARS) must match.
# \x01 = enter icon, \x02 = backspace icon, \x03 = bar segment, \x04 = full
# heart, \x05 = empty heart, \x06 = solid 8x8 block
FONT_CHARS = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!?:.-/%><#',\x01\x02\x03\x04\x05\x06+=*()"

GLYPHS = {
" ": """
......
......
......
......
......
......
......
""",
"A": """
.####.
#....#
#....#
######
#....#
#....#
#....#
""",
"B": """
#####.
#....#
#....#
#####.
#....#
#....#
#####.
""",
"C": """
.####.
#....#
#.....
#.....
#.....
#....#
.####.
""",
"D": """
#####.
#....#
#....#
#....#
#....#
#....#
#####.
""",
"E": """
######
#.....
#.....
#####.
#.....
#.....
######
""",
"F": """
######
#.....
#.....
#####.
#.....
#.....
#.....
""",
"G": """
.####.
#....#
#.....
#..###
#....#
#....#
.####.
""",
"H": """
#....#
#....#
#....#
######
#....#
#....#
#....#
""",
"I": """
.####.
..##..
..##..
..##..
..##..
..##..
.####.
""",
"J": """
..####
....#.
....#.
....#.
....#.
#...#.
.###..
""",
"K": """
#....#
#...#.
#..#..
###...
#..#..
#...#.
#....#
""",
"L": """
#.....
#.....
#.....
#.....
#.....
#.....
######
""",
"M": """
#....#
##..##
#.##.#
#.##.#
#....#
#....#
#....#
""",
"N": """
#....#
##...#
#.#..#
#..#.#
#...##
#....#
#....#
""",
"O": """
.####.
#....#
#....#
#....#
#....#
#....#
.####.
""",
"P": """
#####.
#....#
#....#
#####.
#.....
#.....
#.....
""",
"Q": """
.####.
#....#
#....#
#....#
#..#.#
#...#.
.###.#
""",
"R": """
#####.
#....#
#....#
#####.
#..#..
#...#.
#....#
""",
"S": """
.#####
#.....
#.....
.####.
.....#
.....#
#####.
""",
"T": """
######
..##..
..##..
..##..
..##..
..##..
..##..
""",
"U": """
#....#
#....#
#....#
#....#
#....#
#....#
.####.
""",
"V": """
#....#
#....#
#....#
#....#
.#..#.
.#..#.
..##..
""",
"W": """
#....#
#....#
#....#
#.##.#
#.##.#
##..##
#....#
""",
"X": """
#....#
#....#
.#..#.
..##..
.#..#.
#....#
#....#
""",
"Y": """
#....#
#....#
.#..#.
..##..
..##..
..##..
..##..
""",
"Z": """
######
.....#
....#.
...#..
..#...
.#....
######
""",
"0": """
.####.
#....#
#...##
#.#..#
##...#
#....#
.####.
""",
"1": """
..##..
.###..
..##..
..##..
..##..
..##..
######
""",
"2": """
.####.
#....#
.....#
...##.
..#...
.#....
######
""",
"3": """
.####.
#....#
.....#
..###.
.....#
#....#
.####.
""",
"4": """
....#.
...##.
..#.#.
.#..#.
######
....#.
....#.
""",
"5": """
######
#.....
#.....
#####.
.....#
#....#
.####.
""",
"6": """
.####.
#.....
#.....
#####.
#....#
#....#
.####.
""",
"7": """
######
.....#
....#.
...#..
..#...
..#...
..#...
""",
"8": """
.####.
#....#
#....#
.####.
#....#
#....#
.####.
""",
"9": """
.####.
#....#
#....#
.#####
.....#
.....#
.####.
""",
"!": """
..##..
..##..
..##..
..##..
..##..
......
..##..
""",
"?": """
.####.
#....#
.....#
...##.
..#...
......
..#...
""",
":": """
......
..##..
..##..
......
..##..
..##..
......
""",
".": """
......
......
......
......
......
..##..
..##..
""",
"-": """
......
......
......
.####.
......
......
......
""",
"/": """
.....#
....#.
...#..
..#...
.#....
#.....
......
""",
"%": """
##...#
##..#.
...#..
..#...
.#....
#..##.
#..##.
""",
">": """
#.....
.#....
..#...
...#..
..#...
.#....
#.....
""",
"<": """
...#..
..#...
.#....
#.....
.#....
..#...
...#..
""",
"#": """
.#..#.
.#..#.
######
.#..#.
######
.#..#.
.#..#.
""",
"'": """
..##..
..##..
...#..
......
......
......
......
""",
",": """
......
......
......
......
..##..
..##..
.#....
""",
# enter icon (return arrow)
"\x01": """
.....#
.....#
..#..#
.#...#
######
.#....
..#...
""",
# backspace icon (left arrow)
"\x02": """
......
..#...
.#....
######
.#....
..#...
......
""",
# bar segment (stat bars); drawn 8 px wide by blit_glyph
"\x03": """
######
######
######
######
######
######
######
""",
# full heart
"\x04": """
.#..#.
######
######
######
.####.
..##..
......
""",
# solid block (drawn by blit_glyph directly)
"\x06": """
######
######
######
######
######
######
######
""",
# empty heart
"\x05": """
.#..#.
#.##.#
#....#
#....#
.#..#.
..##..
......
""",
"+": """
......
..##..
..##..
######
######
..##..
..##..
""",
"=": """
......
......
######
......
......
######
......
""",
"*": """
......
#.#.#.
.###..
#####.
.###..
#.#.#.
......
""",
"(": """
...#..
..#...
.#....
.#....
.#....
..#...
...#..
""",
")": """
..#...
...#..
....#.
....#.
....#.
...#..
..#...
""",
}

GLYPH_W, GLYPH_H = 6, 7


def glyph_rows(ch):
    rows = [r for r in GLYPHS[ch].strip("\n").split("\n")]
    assert len(rows) == GLYPH_H, f"glyph {ch!r}: {len(rows)} rows"
    for r in rows:
        assert len(r) == GLYPH_W, f"glyph {ch!r}: bad row {r!r}"
    return rows


def blit_glyph(px, ch, x0, y0, color):
    if ch == "\x03":                  # bar segment: full width, rows 1-6
        for y in range(1, 7):
            for x in range(8):
                px[x0 - 1 + x, y0 + y] = color
        return
    if ch == "\x06":                  # solid block: the whole tile
        for y in range(8):
            for x in range(8):
                px[x0 - 1 + x, y0 + y] = color
        return
    for y, row in enumerate(glyph_rows(ch)):
        for x, c in enumerate(row):
            if c == "#":
                px[x0 + x, y0 + y] = color


def new_indexed(w, h, palette):
    img = Image.new("P", (w, h), 0)
    flat = []
    for rgb in palette:
        flat += list(rgb)
    flat += [0, 0, 0] * (256 - len(palette))
    img.putpalette(flat)
    return img


def blit_art(px, art, x0, y0, colors):
    """Paste ASCII art: '.' transparent, other characters looked up in colors."""
    rows = art.strip("\n").split("\n")
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            if c != ".":
                px[x0 + x, y0 + y] = colors[c]


MAGENTA = (255, 0, 255)


def write_opts(name, text):
    """png2gba options that go with an asset (always LF, the Makefile cats them)."""
    with open(os.path.join(ASSETS, name), "w", newline="\n") as f:
        f.write(text + "\n")


def make_font():
    """8x8 glyph strip, one tile per character of FONT_CHARS (ink = 1)."""
    n = len(FONT_CHARS)
    img = new_indexed(8 * n, 8, [MAGENTA, (255, 255, 255)])
    px = img.load()
    for i, ch in enumerate(FONT_CHARS):
        blit_glyph(px, ch, i * 8 + 1, 0, 1)
    img.save(os.path.join(ASSETS, "font.png"))


# --- grid cells ---------------------------------------------------------------
# 16 metatiles of 16x16: index = thick-edge bits (1 = north, 2 = east,
# 4 = south, 8 = west). Palette: 1 fill, 2 light bevel, 3 dark bevel/grid
# line, 4 region edge. Each rock region gets its own palette bank at run time.
CELL_PAL = [MAGENTA, (150, 120, 90), (185, 155, 120), (95, 72, 50), (30, 22, 16)]


def draw_cell(px, x0, y0, edges):
    for y in range(16):
        for x in range(16):
            c = 1
            if x == 0 or y == 0:
                c = 2
            if x == 15 or y == 15:
                c = 3
            px[x0 + x, y0 + y] = c
    if edges & 1:
        for x in range(16):
            for y in range(2): px[x0 + x, y0 + y] = 4
    if edges & 4:
        for x in range(16):
            for y in range(14, 16): px[x0 + x, y0 + y] = 4
    if edges & 8:
        for y in range(16):
            for x in range(2): px[x0 + x, y0 + y] = 4
    if edges & 2:
        for y in range(16):
            for x in range(14, 16): px[x0 + x, y0 + y] = 4


def draw_tunnel(px, x0, y0, links):
    """Dug gallery: rock cell with a dark floor opening towards linked sides
    (1 N, 2 E, 4 S, 8 W). Floor = 4, rim = 3."""
    draw_cell(px, x0, y0, 0)
    def floor(x, y):
        px[x0 + x, y0 + y] = 4
    for y in range(4, 12):
        for x in range(4, 12):
            floor(x, y)
    if links & 1:
        for y in range(0, 4):
            for x in range(4, 12): floor(x, y)
    if links & 4:
        for y in range(12, 16):
            for x in range(4, 12): floor(x, y)
    if links & 8:
        for y in range(4, 12):
            for x in range(0, 4): floor(x, y)
    if links & 2:
        for y in range(4, 12):
            for x in range(12, 16): floor(x, y)
    # rim: every rock pixel touching the floor becomes the dark bevel colour
    for y in range(16):
        for x in range(16):
            if px[x0 + x, y0 + y] == 4:
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                xx, yy = x + dx, y + dy
                if 0 <= xx < 16 and 0 <= yy < 16 and px[x0 + xx, y0 + yy] == 4:
                    px[x0 + x, y0 + y] = 3
                    break


def make_cells():
    """32 metatiles: 16 rock cells by thick-edge bits, then 16 dug galleries by link bits."""
    img = new_indexed(16 * 32, 16, CELL_PAL)
    px = img.load()
    for e in range(16):
        draw_cell(px, e * 16, 0, e)
    for links in range(16):
        draw_tunnel(px, (16 + links) * 16, 0, links)
    img.save(os.path.join(ASSETS, "cells.png"))
    write_opts("cells.opts", "--meta 2 2")


# --- marks (overlay on top of the cells) -------------------------------------------
# 16x16 metatiles. Palette: 1 dark ink, 2 light ink, 3 alert, 4 gold.
MARK_PAL = [MAGENTA, (30, 22, 16), (245, 240, 225), (220, 50, 40), (240, 200, 60)]
MARK_ART = {
"cross": """
................
................
................
....d......d....
.....d....d.....
......d..d......
.......dd.......
.......dd.......
......d..d......
.....d....d.....
....d......d....
................
................
................
................
................
""",
"dig": """
................
..........dd....
.........dldd...
........dlldd...
.......dlldddd..
......dlld..dd..
.....dlld....d..
....dlld........
...dlld.........
..dlld..........
..dld...........
..dd............
.dddddd.........
dddddddd........
dddddddd........
.dddddd.........
""",
"alert": """
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aa............aa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
""",
"gem": """
................
................
................
.....gggggg.....
....glllllgg....
...gllggggggg...
...glgggggggg...
...gggggggggg...
....gggggggg....
.....gggggg.....
......gggg......
.......gg.......
................
................
................
................
""",
"ore_light": """
................
................
................
.....llllll.....
....llllllll....
...llllllllll...
...lllllllddl...
...llllllllll...
...llllllllll...
...dllllllllld..
....dlllllllld..
.....dddddddd...
................
................
................
................
""",
"ore_dark": """
................
................
................
.....dddddd.....
....dddddddd....
...dddddddddd...
...dddlddddd....
...ddddddddddd..
...dddddddddd...
...dddddddddd...
....dddddddd....
.....dddddd.....
................
................
................
................
""",
"ghost_ok": """
g.g.g.g.g.g.g.g.
................
g..............g
................
g..............g
................
g..............g
................
g..............g
................
g..............g
................
g..............g
................
g..............g
.g.g.g.g.g.g.g.g
""",
"ghost_bad": """
a.a.a.a.a.a.a.a.
................
a..............a
................
a..............a
................
a..............a
................
a..............a
................
a..............a
................
a..............a
................
a..............a
.a.a.a.a.a.a.a.a
""",
"burst1": """
................
................
................
................
................
......ll........
.....llll.......
.....lgll.......
......ll........
................
................
................
................
................
................
................
""",
"burst2": """
................
................
.....g..g.......
....l.ll.l......
.....llll.......
....llgglla.....
...allggll......
.....llll.......
....l.ll.l......
.....g..g.......
................
................
................
................
................
................
""",
"burst3": """
..a..........a..
...a...ll...a...
....a..ll..a....
.....a....a.....
..a....gg....a..
...a..gllg..a...
.ll..gl..lg..ll.
.ll..gl..lg..ll.
...a..gllg..a...
..a....gg....a..
.....a....a.....
....a..ll..a....
...a...ll...a...
..a..........a..
................
................
""",
}
MARK_ORDER = ["empty", "cross", "dig", "alert", "gem", "ore_light", "ore_dark",
              "ghost_ok", "ghost_bad", "burst1", "burst2", "burst3"]


MARK_NUMBERS = 12                 # number marks 1..12 follow the named marks (MARK_DIGIT1 in render.h)


def blit_big_digit(px, ch, x0, y0, color, shadow):
    """Font glyph scaled x2 (12x14) centred in a 16x16 cell, with a 1 px drop shadow."""
    rows = glyph_rows(ch)
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            if c != "#":
                continue
            for dy in range(2):
                for dx in range(2):
                    px[x0 + 2 + 2 * x + dx + 1, y0 + 1 + 2 * y + dy + 1] = shadow
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            if c != "#":
                continue
            for dy in range(2):
                for dx in range(2):
                    px[x0 + 2 + 2 * x + dx, y0 + 1 + 2 * y + dy] = color


def blit_small_number(px, text, x0, y0, color, shadow):
    """Two 1x glyphs (6 px each) side by side, centred, with a drop shadow."""
    w = 6 * len(text) - 1
    left = x0 + (16 - w) // 2
    for pass_color, off in ((shadow, 1), (color, 0)):
        for k, ch in enumerate(text):
            for y, row in enumerate(glyph_rows(ch)):
                for x, c in enumerate(row):
                    if c == "#":
                        px[left + 6 * k + x + off, y0 + 4 + y + off] = pass_color


def make_marks():
    """Named marks, then number marks 1..MARK_NUMBERS (big digits up to 9, two small digits after)."""
    n = len(MARK_ORDER) + MARK_NUMBERS
    img = new_indexed(16 * n, 16, MARK_PAL)
    px = img.load()
    colors = {"d": 1, "l": 2, "a": 3, "g": 4, "t": 3}
    for i, name in enumerate(MARK_ORDER):
        if name != "empty":
            blit_art(px, MARK_ART[name], i * 16, 0, colors)
    for k in range(MARK_NUMBERS):
        x0 = (len(MARK_ORDER) + k) * 16
        if k + 1 <= 9:
            blit_big_digit(px, str(k + 1), x0, 0, 2, 1)
        else:
            blit_small_number(px, str(k + 1), x0, 0, 2, 1)
    img.save(os.path.join(ASSETS, "marks.png"))
    write_opts("marks.opts", "--meta 2 2")


# --- cursor sprite (2 frames of 16x16) -----------------------------------------------
CURSOR = """
wwwww......wwwww
w..............w
w..............w
w..............w
w..............w
................
................
................
................
................
................
w..............w
w..............w
w..............w
w..............w
wwwww......wwwww
"""
CURSOR2 = """
wwww........wwww
w..............w
w..............w
w..............w
................
................
................
................
................
................
................
................
w..............w
w..............w
w..............w
wwww........wwww
"""


def make_cursor():
    img = new_indexed(32, 16, [MAGENTA, (255, 255, 255)])
    px = img.load()
    blit_art(px, CURSOR, 0, 0, {"w": 1})
    blit_art(px, CURSOR2, 16, 0, {"w": 1})
    img.save(os.path.join(ASSETS, "cursor.png"))
    write_opts("cursor.opts", "--meta 2 2")


# --- dwarf sprite (16x16, frames: idle A, idle B, dig A, dig B) ------------------------
# Boxy silhouette after Dwarves Manager: square head, wide beard, round helmet.
# Palette: 1 outline, 2 skin, 3 beard, 4 tunic, 5 helmet, 6 pick metal
DWARF_PAL = [MAGENTA, (30, 22, 16), (250, 205, 150), (140, 80, 40), (90, 120, 70), (110, 110, 120), (200, 200, 210)]
DWARF_IDLE_A = """
.....oooooo.....
....ohhhhhho....
...ohhhhhhhho...
...ooooooooo....
...osssssssso...
...osoossooso...
...ossssssso....
...obbbbbbbo....
..obbbbbbbbbo...
..obbbbbbbbbo...
...obbbbbbbo....
...ottttttto....
...ottttttto....
...ottttttto....
...oo.....oo....
...oo.....oo....
"""
DWARF_IDLE_B = """
................
.....oooooo.....
....ohhhhhho....
...ohhhhhhhho...
...ooooooooo....
...osssssssso...
...osoossooso...
...ossssssso....
...obbbbbbbo....
..obbbbbbbbbo...
..obbbbbbbbbo...
...obbbbbbbo....
...ottttttto....
...ottttttto....
...ottttttto....
...oo.....oo....
"""
DWARF_DIG_A = """
.....oooooo...om
....ohhhhhho..om
...ohhhhhhhho.om
...ooooooooo..o.
...osssssssso.o.
...osoossoosoo..
...osssssssoo...
...obbbbbbbo....
..obbbbbbbbbo...
..obbbbbbbbbo...
...obbbbbbbo....
...ottttttto....
...ottttttto....
...ottttttto....
...oo.....oo....
...oo.....oo....
"""
DWARF_DIG_B = """
................
.....oooooo.....
....ohhhhhho....
...ohhhhhhhho...
...ooooooooo....
...osssssssso...
...osoossooso...
...ossssssso....
...obbbbbbbo....
..obbbbbbbbbo...
..obbbbbbbbbooo.
...obbbbbbbo..o.
...ottttttto..o.
...ottttttto.omm
...oo.....oo.omm
...oo.....oo....
"""


def make_dwarf():
    frames = [DWARF_IDLE_A, DWARF_IDLE_B, DWARF_DIG_A, DWARF_DIG_B]
    img = new_indexed(16 * len(frames), 16, DWARF_PAL)
    px = img.load()
    colors = {"o": 1, "s": 2, "b": 3, "t": 4, "h": 5, "m": 6}
    for i, art in enumerate(frames):
        blit_art(px, art, i * 16, 0, colors)
    img.save(os.path.join(ASSETS, "dwarf.png"))
    write_opts("dwarf.opts", "--meta 2 2")


# --- biome backdrops --------------------------------------------------------------
# A strip of 16 variants of a 64x64 block per biome (assets/back_<biome>.png, --meta 8 8),
# drawn procedurally from a tiny seeded generator. Palette indices 4..15 only:
# they share BG palette bank 11 with the canvas lines (1..3). Kept dark so the
# UI text stays readable on top. Final art: same size, same index range.
BIOMES = ["earth", "rock", "ice", "lava", "crystal", "core"]


class Rng:
    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def next(self):
        self.s = (self.s * 1103515245 + 12345) & 0x7FFFFFFF
        return self.s >> 8

    def below(self, n):
        return self.next() % n


def ramp(dark, light, steps):
    """Colours interpolated from dark to light (steps entries)."""
    out = []
    for i in range(steps):
        t = i / max(1, steps - 1)
        out.append(tuple(int(dark[k] + (light[k] - dark[k]) * t) for k in range(3)))
    return out


def backdrop_pixels(biome, rng):
    """32x32 grid of palette indices 4..15 for a biome (wraps seamlessly)."""
    W = 32
    px = [[4] * W for _ in range(W)]

    def wrap(v):
        return v % W

    def blob(cx, cy, r, val, hollow=False):
        for y in range(-r, r + 1):
            for x in range(-r, r + 1):
                d2 = x * x + y * y
                if d2 <= r * r and (not hollow or d2 >= (r - 1) * (r - 1)):
                    px[wrap(cy + y)][wrap(cx + x)] = val

    if biome == "earth":
        for y in range(W):
            for x in range(W):
                px[y][x] = 4 + (rng.below(6) == 0) + (rng.below(9) == 0)   # grainy dirt 4..6
        for _ in range(7):                                                   # pebbles
            blob(rng.below(W), rng.below(W), 1 + rng.below(2), 8)
        for _ in range(3):                                                   # roots
            x, y = rng.below(W), rng.below(W)
            for k in range(10):
                px[wrap(y + k)][wrap(x + (k // 3) % 2)] = 7
    elif biome == "rock":
        for y in range(W):
            band = 4 + ((y // 5) % 3)                                        # strata
            for x in range(W):
                px[y][x] = band + (rng.below(7) == 0)
        for y in range(4, W, 9):                                             # cracks along strata
            x0 = rng.below(W)
            for k in range(6 + rng.below(8)):
                px[wrap(y + (k % 4 == 3))][wrap(x0 + k)] = 8
    elif biome == "ice":
        for y in range(W):
            for x in range(W):
                px[y][x] = 4 + ((x + y) // 11) % 2
        for _ in range(4):                                                   # diagonal cracks
            x, y = rng.below(W), rng.below(W)
            for k in range(8 + rng.below(8)):
                px[wrap(y + k)][wrap(x + k)] = 7
                if k % 5 == 2:
                    px[wrap(y + k)][wrap(x + k + 1)] = 8
        for _ in range(3):                                                   # glints
            blob(rng.below(W), rng.below(W), 0, 9)
    elif biome == "lava":
        for y in range(W):
            for x in range(W):
                px[y][x] = 4 + (rng.below(5) == 0)
        for _ in range(3):                                                   # glowing veins
            x, y = rng.below(W), rng.below(W)
            for k in range(14):
                px[wrap(y + k)][wrap(x)] = 8
                px[wrap(y + k)][wrap(x + 1)] = 7
                if k % 4 == 1:
                    x += 1 if rng.below(2) else -1
        for _ in range(3):                                                   # bubbles
            blob(rng.below(W), rng.below(W), 2, 6, hollow=True)
            blob(rng.below(W), rng.below(W), 1, 9)
    elif biome == "crystal":
        for y in range(W):
            for x in range(W):
                px[y][x] = 4 + (rng.below(8) == 0)
        for _ in range(5):                                                   # facets: diamonds
            cx, cy, r = rng.below(W), rng.below(W), 2 + rng.below(3)
            for y in range(-r, r + 1):
                for x in range(-r, r + 1):
                    if abs(x) + abs(y) == r:
                        px[wrap(cy + y)][wrap(cx + x)] = 7
                    elif abs(x) + abs(y) < r:
                        px[wrap(cy + y)][wrap(cx + x)] = 6 if x + y > 0 else 8
            px[wrap(cy - 1)][wrap(cx)] = 9
    else:  # core
        for y in range(W):
            for x in range(W):
                px[y][x] = 4 + (rng.below(6) == 0)
        for r in (5, 10, 15):                                                # concentric glow rings
            blob(16, 16, r, 7 if r != 10 else 8, hollow=True)
        blob(16, 16, 2, 9)
        for _ in range(4):
            blob(rng.below(W), rng.below(W), 0, 8)
    return px


BACKDROP_PALS = {
    # indices 4..9 used above: base, base+, dark detail, line, bright line, glint
    "earth":   [(38, 26, 16), (46, 32, 20), (30, 20, 12), (60, 42, 24), (70, 58, 40), (90, 78, 50)],
    "rock":    [(30, 30, 34), (36, 36, 40), (42, 42, 48), (22, 22, 26), (56, 56, 64), (80, 80, 90)],
    "ice":     [(16, 30, 48), (20, 38, 58), (24, 44, 70), (60, 90, 120), (90, 130, 160), (150, 190, 220)],
    "lava":    [(42, 10, 8), (52, 14, 10), (30, 6, 6), (120, 40, 10), (170, 70, 10), (230, 150, 40)],
    "crystal": [(28, 14, 40), (34, 18, 50), (60, 30, 90), (90, 50, 130), (44, 24, 64), (170, 120, 210)],
    "core":    [(48, 16, 4), (58, 22, 6), (36, 12, 2), (110, 40, 8), (160, 70, 12), (240, 170, 60)],
}


def make_backdrops():
    for i, biome in enumerate(BIOMES):
        rng = Rng(1000 + 77 * i)
        pal = [MAGENTA, (0, 0, 0), (0, 0, 0), (0, 0, 0)] + BACKDROP_PALS[biome]
        pal += [(0, 0, 0)] * (16 - len(pal))
        img = new_indexed(64 * 16, 64, pal)
        px = img.load()
        for v in range(16):                       # 16 variants: a 32 px noise block repeated 2x2
            grid = backdrop_pixels(biome, rng)
            for y in range(64):
                for x in range(64):
                    px[v * 64 + x, y] = grid[y % 32][x % 32]
        img.save(os.path.join(ASSETS, f"back_{biome}.png"))
        write_opts(f"back_{biome}.opts", "--meta 8 8")


# --- merchant dwarf (32x32, 2 frames) -------------------------------------------------
# The shopkeeper: same boxy family, taller, a cap, an apron and a lamp.
# Palette: 1 outline, 2 skin, 3 beard, 4 apron, 5 cap, 6 lamp glow, 7 tunic
MERCHANT_PAL = [MAGENTA, (30, 22, 16), (250, 205, 150), (200, 200, 205), (120, 70, 40), (150, 40, 40), (250, 220, 90), (70, 90, 110)]
MERCHANT_A = """
..........oooooooooo............
.........occccccccccco..........
........occcccccccccccoo........
........oooooooooooooooo........
.........osssssssssssso.........
.........osoossssssoosso........
.........ossssssssssssso........
.........ossssoooosssso.........
..........osssssssssso..........
.........obbbbbbbbbbbbo.........
........obbbbbbbbbbbbbbo........
.......obbbbbbbbbbbbbbbbo.......
.......obbbbbbbbbbbbbbbbo.......
........obbbbbbbbbbbbbbo........
.........obbbbbbbbbbbbo.........
......ooottttttttttttttooo......
.....otttaaaaaaaaaaaattttto.....
.....ottaaaaaaaaaaaaaatttto.....
.....ottaaaaaaaaaaaaaattoo......
.....ottaaaaaaaaaaaaaattoll.....
.....ottaaaaaaaaaaaaaattolll....
.....ottaaaaaaaaaaaaaattoll.....
......oaaaaaaaaaaaaaaaoooo......
......oaaaaaaaaaaaaaaao.........
......oaaaaaaaaaaaaaaao.........
......oaaaaaaaaaaaaaaao.........
.......ooooooooooooooo..........
.......ooo........ooo...........
.......ooo........ooo...........
......oooo........oooo..........
......oooo........oooo..........
................................
"""
MERCHANT_B = """
................................
..........oooooooooo............
.........occccccccccco..........
........occcccccccccccoo........
........oooooooooooooooo........
.........osssssssssssso.........
.........osoossssssoosso........
.........ossssssssssssso........
.........ossssoooosssso.........
..........osssssssssso..........
.........obbbbbbbbbbbbo.........
........obbbbbbbbbbbbbbo........
.......obbbbbbbbbbbbbbbbo.......
.......obbbbbbbbbbbbbbbbo.......
........obbbbbbbbbbbbbbo........
......ooottttttttttttttooo......
.....otttaaaaaaaaaaaattttto.....
.....ottaaaaaaaaaaaaaatttto.....
.....ottaaaaaaaaaaaaaattoo......
.....ottaaaaaaaaaaaaaattol......
.....ottaaaaaaaaaaaaaattolll....
.....ottaaaaaaaaaaaaaattolll....
......oaaaaaaaaaaaaaaaoool......
......oaaaaaaaaaaaaaaao.........
......oaaaaaaaaaaaaaaao.........
......oaaaaaaaaaaaaaaao.........
.......ooooooooooooooo..........
.......ooo........ooo...........
.......ooo........ooo...........
......oooo........oooo..........
......oooo........oooo..........
................................
"""


def make_merchant():
    frames = [MERCHANT_A, MERCHANT_B]
    img = new_indexed(32 * len(frames), 32, MERCHANT_PAL)
    px = img.load()
    colors = {"o": 1, "s": 2, "b": 3, "a": 4, "c": 5, "l": 6, "t": 7}
    for i, art in enumerate(frames):
        blit_art(px, art, i * 32, 0, colors)
    img.save(os.path.join(ASSETS, "merchant.png"))
    write_opts("merchant.opts", "--meta 4 4")


# --- title logo (128x32, two 64x32 sprites) -------------------------------------------------
# "DEEPER" from the font glyphs scaled x3 with a drop shadow and a lit top row.
# Palette: 1 shadow, 2 body, 3 highlight.
LOGO_PAL = [MAGENTA, (40, 24, 8), (240, 200, 60), (255, 240, 170)]


def make_logo():
    img = new_indexed(128, 32, LOGO_PAL)
    px = img.load()
    word = "DEEPER"
    scale = 3
    w = len(word) * (GLYPH_W * scale) + (len(word) - 1) * 2
    x0 = (128 - w) // 2
    y0 = (32 - GLYPH_H * scale) // 2
    for k, ch in enumerate(word):
        gx = x0 + k * (GLYPH_W * scale + 2)
        rows = glyph_rows(ch)
        for pass_color, dx, dy in ((1, 2, 2), (2, 0, 0)):
            for y, row in enumerate(rows):
                for x, c in enumerate(row):
                    if c != "#":
                        continue
                    for sy in range(scale):
                        for sx in range(scale):
                            X, Y = gx + x * scale + sx + dx, y0 + y * scale + sy + dy
                            if 0 <= X < 128 and 0 <= Y < 32:
                                if pass_color == 2 and sy == 0 and (y == 0 or rows[y - 1][x] != "#"):
                                    px[X, Y] = 3
                                else:
                                    px[X, Y] = pass_color
    img.save(os.path.join(ASSETS, "logo.png"))
    write_opts("logo.opts", "--meta 8 4")


# --- title menu icons (32x32): continue, new descent, counter, logbook -----------------------
# Palette: 1 outline, 2 light, 3 gold, 4 brown, 5 red, 6 grey, 7 blue
MENU_PAL = [MAGENTA, (30, 22, 16), (240, 235, 220), (240, 200, 60), (140, 80, 40), (200, 60, 50), (150, 150, 160), (90, 150, 220)]
MENU_ART = {
"continue": """
................................
................................
............ooo.................
...........ollo.................
..........ollllo................
..........olgglo................
..........olgglo................
..........ollllo................
...........oooo.................
............oo..................
............oo......oooo........
.....ooooooooooooooollllo.......
....oggggggggggggggggllllo......
....ogggggggggggggggggllllo.....
.....oooooooooooooooollllo......
....................ollllo......
....................oooo........
............oo..................
............oo..................
............oo..................
...........oooo.................
..........obbbbo................
..........obbbbo................
..........obbbbo................
...........oooo.................
................................
................................
................................
................................
................................
................................
................................
""",
"new": """
................................
................................
......................ooo.......
.....................ogggo......
....................ogggggo.....
...................ogggggggo....
..................oggggggggo....
.................ogggggggoo.....
................oggggooooo......
...............ogggoo...........
..............ogggo.............
.............ogggo..............
............ogggo...............
...........ogggo................
..........ogggo.................
.........ogggo..................
........ogggo...................
.......obbbo....................
......obbbo.....................
.....obbbo......................
....obbbo.......................
...obbbo........................
..obbbo.........................
..obbo..........................
...oo...........................
................................
..........oooooooooooooooo......
.........ollllllllllllllllo.....
.........olllllllooooollllo.....
.........ollllllooooooolllo.....
..........oooooooooooooooo......
................................
""",
"shop": """
................................
................................
.............oooooo.............
............orrrrrro............
...........orrrrrrrro...........
..........orrrrrrrrrro..........
.........orrrrrrrrrrrro.........
.........oooooooooooooo.........
..........ossssssssssso.........
..........osooossssooso.........
..........ossssssssssso.........
...........oooooooooooo.........
..........obbbbbbbbbbbbo........
.........obbbbbbbbbbbbbbo.......
.........obbbbbbbbbbbbbbo.......
..........obbbbbbbbbbbbo........
......oooooooooooooooooooooo....
.....olllllllllllllllllllllllo..
.....ollggggggggggggggggggllo...
.....ollggggggggggggggggggllo...
.....ollggggggggggggggggggllo...
.....ollggggggggggggggggggllo...
.....ollggggggggggggggggggllo...
......oooooooooooooooooooooo....
.......oo................oo.....
.......oo................oo.....
.......oo................oo.....
......oooo..............oooo....
................................
................................
................................
................................
""",
"records": """
................................
................................
................................
.......oooooooooooooooooo.......
......ollllllllllllllllllo......
......olooooooooooooooollo......
......olollllllllllllololo......
......olollggggggllllololo......
......olollllllllllllololo......
......olollgggggggglloolo.......
......olollllllllllllololo......
......olollggggllllllololo......
......olollllllllllllololo......
......olollgggggggggloolo.......
......olollllllllllllololo......
......olollggggggglllololo......
......olollllllllllllololo......
......olooooooooooooooollo......
......ollllllllllllllllllo......
......olbbbbbbbbbbbbbbbblo......
......olbbbbbbbbbbbbbbbblo......
.......oooooooooooooooooo.......
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
""",
"options": """
................................
................................
..............oooo..............
.......oo....oeeeeo....oo.......
......oeeo..oeeeeeeo..oeeo......
......oeeeooeeeeeeeeooeeeo......
.......oeeeeeeeeeeeeeeeeo.......
........oeeeeeeeeeeeeeeo........
.....oooeeeeeoooooeeeeeooo......
....oeeeeeeeoolllloeeeeeeeo.....
....oeeeeeeolllllllloeeeeeo.....
.....oooeeeolllllllloeeeooo.....
........oeeolllllllloeeo........
.....oooeeeolllllllloeeeooo.....
....oeeeeeeolllllllloeeeeeo.....
....oeeeeeeeoolllloeeeeeeeo.....
.....oooeeeeeoooooeeeeeooo......
........oeeeeeeeeeeeeeeo........
.......oeeeeeeeeeeeeeeeeo.......
......oeeeooeeeeeeeeooeeeo......
......oeeo..oeeeeeeo..oeeo......
.......oo....oeeeeo....oo.......
..............oooo..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
""",
}
MENU_ORDER = ["continue", "new", "shop", "records", "options"]


def make_menu_icons():
    img = new_indexed(32 * len(MENU_ORDER), 32, MENU_PAL)
    px = img.load()
    colors = {"o": 1, "l": 2, "g": 3, "b": 4, "r": 5, "s": 2, "e": 6, "u": 7}
    for i, name in enumerate(MENU_ORDER):
        blit_art(px, MENU_ART[name], i * 32, 0, colors)
    img.save(os.path.join(ASSETS, "menu_icons.png"))
    write_opts("menu_icons.opts", "--meta 4 4")


# --- GBA button icons (16x16 metatiles): A, B, L, R, START, SELECT, D-pad ------------------------
# Drawn on the text layer next to their labels (help screens). Palette as marks:
# 1 dark ink, 2 light face, 3 alert, 4 gold.
BUTTON_ART = {
"A": """
.....dddddd.....
...ddllllllldd..
..dllllllllllld.
.dlllllllllllld.
.dllllldlllllld.
dllllldldllllld.
dlllllddddlllld.
dlllldlllldllld.
dllldllllldllld.
dllddllllllddld.
dllllllllllllld.
.dlllllllllllld.
.dlllllllllllld.
..dllllllllllld.
...ddllllllldd..
.....dddddd.....
""",
"B": """
.....dddddd.....
...ddllllllldd..
..dllllllllllld.
.dllldddddlllld.
.dlllldlllldlld.
dllllldlllldlld.
dllllldddddllld.
dllllldlllldlld.
dllllldllllldld.
dllllldlllldlld.
dllllddddddllld.
.dlllllllllllld.
.dlllllllllllld.
..dllllllllllld.
...ddllllllldd..
.....dddddd.....
""",
"L": """
..dddddddddddd..
.dllllllllllllld
dlllllllllllllld
dllllldlllllllld
dllllldlllllllld
dllllldlllllllld
dllllldlllllllld
dlllllddddlllld.
dllllllllllllld.
.dllllllllllldd.
..dddddddddddd..
................
................
................
................
................
""",
"R": """
..dddddddddddd..
dlllllllllllllld
dlllllllllllllld
dllllddddlllllld
dlllldlllldlllld
dlllldddddllllld
dlllldlldlllllld
.dllldllldllllld
.dllllllllllllld
.ddllllllllllld.
..dddddddddddd..
................
................
................
................
................
""",
"START": """
................
................
................
....dddddddd....
..ddllllllllldd.
.dlllllllllllld.
dlllllllllllllld
.dlllllllllllld.
..ddllllllllldd.
....dddddddd....
................
.dd.d.d.dd.d.dd.
.d..d.dd.d.d.d..
.dd.d.ddd.dd.d..
................
................
""",
"SELECT": """
................
................
................
....dddddddd....
..ddllllllllldd.
.dlllllllllllld.
dlllllllllllllld
.dlllllllllllld.
..ddllllllllldd.
....dddddddd....
................
.dd.dd.d..dd.dd.
.d..d..d..d..d..
.dd.dd.dd.dd.d..
................
................
""",
"DPAD": """
......dddd......
.....dllllld....
.....dldlldl....
.....dllllld....
.....dllllld....
.ddddllllllddddd
dlldlllllllldlld
dllllllllllllll
dlllllllllllllld
.ddddllllllddddd
.....dllllld....
.....dllllld....
.....dldlldl....
.....dllllld....
......dddd......
................
""",
"UP": """
................
.......dd.......
......dlld......
.....dllttd.....
....dlltlttd....
...dlltlltttd...
..dlltlllltttd..
.dddddlllldddd..
.....dlllld.....
.....dlllld.....
.....dlllld.....
.....dlllld.....
.....dlllld.....
.....dddddd.....
................
................
""",
"DOWN": """
................
................
.....dddddd.....
.....dlllld.....
.....dlllld.....
.....dlllld.....
.....dlllld.....
.....dlllld.....
.dddddlllldddd..
..dlltlllltttd..
...dlltlltttd...
....dlltlttd....
.....dllttd.....
......dlld......
.......dd.......
................
""",
"LEFT": """
................
................
................
.......dd.......
......dld.......
.....dlld.......
....dlllddddddd.
...dllllllllltd.
..dllllllllllld.
...dtttttttttd..
....dtttddddddd.
.....dttd.......
......dtd.......
.......dd.......
................
................
""",
"RIGHT": """
................
................
................
.......dd.......
.......dld......
.......dlld.....
.ddddddddllld...
.dtlllllllllld..
.dllllllllllld..
..dttttttttttd..
.dddddddtttd....
.......dttd.....
.......dtd......
.......dd.......
................
................
""",
}
BUTTON_ORDER = ["A", "B", "L", "R", "START", "SELECT", "DPAD", "UP", "DOWN", "LEFT", "RIGHT"]


def make_buttons():
    img = new_indexed(16 * len(BUTTON_ORDER), 16, MARK_PAL)
    px = img.load()
    colors = {"d": 1, "l": 2, "a": 3, "g": 4, "t": 3}
    for i, name in enumerate(BUTTON_ORDER):
        art = BUTTON_ART[name]
        rows = [r.ljust(16, ".") for r in art.strip("\n").split("\n")]
        blit_art(px, "\n".join(rows), i * 16, 0, colors)
    img.save(os.path.join(ASSETS, "buttons.png"))
    write_opts("buttons.opts", "--meta 2 2")


# --- small cells (8x8) for the core's picture room ------------------------------------
# Tiles: 0 unknown rock, 1 ore, 2 rock note (x), 3 flat fill (index 1), 4 lit ore
# (reveal), 5 flat fill (index 2: dark with the grey text bank).
# Indices as cells.png (1 fill, 2 light bevel, 3 dark bevel, 4 ink), coloured
# per palette bank at run time.
SMALL_CELLS = [
"""
lllllll3
l111111d
l111111d
l111111d
l111111d
l111111d
l111111d
3dddddd3
""", """
d22222ld
2llll22d
2l22222d
2222222d
2222222d
2222222d
2222222d
ddddddd3
""", """
lllllll3
l111111d
l1i111id
l11i1i1d
l111i11d
l11i1i1d
l1i111id
3dddddd3
""", """
11111111
11111111
11111111
11111111
11111111
11111111
11111111
11111111
""", """
22222222
2llll222
2l222222
22222222
22222222
22222222
22222222
22222222
""", """
22222222
22222222
22222222
22222222
22222222
22222222
22222222
22222222
"""]


def make_small_cells():
    img = new_indexed(8 * len(SMALL_CELLS), 8, CELL_PAL)
    px = img.load()
    for i, art in enumerate(SMALL_CELLS):
        blit_art(px, art, 8 * i, 0, {"1": 1, "l": 2, "2": 2, "d": 3, "3": 3, "i": 4})
    img.save(os.path.join(ASSETS, "cells_small.png"))


CURSOR_SMALL = ["""
wwwwwwww
w......w
w......w
w......w
w......w
w......w
w......w
wwwwwwww
""", """
ww....ww
w......w
........
........
........
........
w......w
ww....ww
""", """
........
..bbb...
.bbggb..
.bgggb..
.bbggb..
..bbb...
........
........
""", """
........
........
....gg..
..gggbb.
.ggbbbb.
..bbbb..
...bb...
........
"""]


def make_cursor_small():
    # two cursor frames, then two rock chips (the wall mini-game's particles)
    img = new_indexed(8 * len(CURSOR_SMALL), 8, [MAGENTA, (255, 255, 255), (120, 80, 50), (160, 150, 140)])
    px = img.load()
    for i, art in enumerate(CURSOR_SMALL):
        blit_art(px, art, 8 * i, 0, {"w": 1, "b": 2, "g": 3})
    img.save(os.path.join(ASSETS, "cursor_small.png"))


# --- the core's pictures (assets/heart/<name>.png, 1 bit, 10/12/15 px) ------------------
# '#' = ore. The generator keeps a drawing when every row's clues fit in 7
# characters and every column's in 4 or 5 rows (tools/heart_pictures.py,
# common/heart.c), and pre-reveals cells when it is not solvable line by line.
HEART_PICTURES = {
"gem": """
....##....
...####...
..######..
.########.
##########
.###..###.
..######..
...####...
....##....
....##....
""",
"pick": """
.....#####
....###..#
...##.#...
..##......
.##.......
##........
#.........
#.........
..........
..........
""",
"mug": """
..........
.######...
.######.#.
.######.##
.######.##
.######.##
.######.#.
.######...
..######..
..........
""",
"heart": """
............
..###..###..
.#####.####.
############
############
############
.##########.
..########..
...######...
....####....
.....##.....
............
""",
"lantern": """
.....##.....
....####....
...######...
..########..
..#..##..#..
..#.####.#..
..#.####.#..
..#..##..#..
..########..
...######...
....####....
.....##.....
""",
"cart": """
............
............
.##########.
.##.####.##.
.####..####.
.##########.
.##########.
############
.###....###.
.###....###.
..##....##..
............
""",
"dwarf": """
.....#####.....
....#######....
...#########...
..###########..
..#.###.###.#..
..#..##.##..#..
..###########..
...#########...
...##.....##...
..####...####..
.###########.#.
.#.#########.#.
.#..#######..#.
.#...#####...#.
.....#####.....
""",
"anvil": """
...............
...............
...............
.##############
..############.
...##########..
.....######....
.......####....
.......####....
.......####....
......######...
.....########..
....##########.
...............
...............
""",
}


def make_heart_pictures():
    folder = os.path.join(ASSETS, "heart")
    os.makedirs(folder, exist_ok=True)
    for name, art in HEART_PICTURES.items():
        rows = art.strip("\n").split("\n")
        n = len(rows)
        img = Image.new("L", (n, n), 255)
        px = img.load()
        for y, row in enumerate(rows):
            if len(row) != n:
                raise SystemExit(f"heart picture {name}: row {y} is {len(row)} wide, expected {n}")
            for x, c in enumerate(row):
                if c == "#":
                    px[x, y] = 0
        img.save(os.path.join(folder, f"{name}.png"))


def main():
    os.makedirs(ASSETS, exist_ok=True)
    make_font()
    make_cells()
    make_small_cells()
    make_cursor_small()
    make_heart_pictures()
    make_marks()
    make_cursor()
    make_dwarf()
    make_backdrops()
    make_merchant()
    make_logo()
    make_menu_icons()
    make_buttons()
    print("assets written to", os.path.normpath(ASSETS))


if __name__ == "__main__":
    sys.exit(main())
