#!/usr/bin/env python3
"""WAV -> GBA DirectSound sample (signed 8-bit mono PCM) as a C array.

usage: wav2gba.py track.wav -o outbase [--name SYMBOL] [--rate 10512]

Accepts 8/16/24/32-bit PCM WAV, mono or stereo, any sample rate: channels are
mixed down and the signal is resampled (linear) to the GBA rate when needed.
Drop any WAV in assets/music/ and the Makefile turns it into mus_<name>.c/.h:
    const signed char SYMBOL[]   samples, 4-byte aligned
    #define SYMBOL_len           number of samples
    #define SYMBOL_loop          1 unless the file name starts with "jingle"
The default rate matches MUSIC_TIMER_DIV in source/music.c (16777216/1596).
"""
import argparse
import os
import struct
import sys
import wave


def read_wav(path):
    with wave.open(path, "rb") as w:
        ch, width, rate, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
        raw = w.readframes(n)
    if width == 1:
        samples = [b - 128 for b in raw]                       # unsigned 8-bit
        scale = 1.0
    elif width == 2:
        samples = list(struct.unpack("<%dh" % (len(raw) // 2), raw))
        scale = 1 / 256
    elif width == 3:
        samples = [int.from_bytes(raw[i:i + 3], "little", signed=True) for i in range(0, len(raw), 3)]
        scale = 1 / 65536
    elif width == 4:
        samples = list(struct.unpack("<%di" % (len(raw) // 4), raw))
        scale = 1 / 16777216
    else:
        sys.exit(f"{path}: unsupported sample width {width}")
    if ch > 1:                                                 # mix down
        samples = [sum(samples[i:i + ch]) / ch for i in range(0, len(samples), ch)]
    return [s * scale for s in samples], rate


def resample(samples, src_rate, dst_rate):
    if src_rate == dst_rate:
        return samples
    out_n = int(len(samples) * dst_rate / src_rate)
    out = []
    step = src_rate / dst_rate
    last = len(samples) - 1
    for i in range(out_n):
        pos = i * step
        k = int(pos)
        frac = pos - k
        a = samples[k]
        b = samples[k + 1] if k < last else a
        out.append(a + (b - a) * frac)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("input")
    ap.add_argument("-o", "--out", required=True, help="output base path (no extension)")
    ap.add_argument("--name", help="C symbol (default: derived from the output name)")
    ap.add_argument("--rate", type=int, default=10512)
    ap.add_argument("--wav", help="also write the converted track as an 8-bit mono WAV (the ROM's exact data; a compact source to commit)")
    a = ap.parse_args()

    samples, rate = read_wav(a.input)
    samples = resample(samples, rate, a.rate)
    data = bytearray()
    for s in samples:
        v = int(round(s))
        data.append((max(-128, min(127, v))) & 0xFF)
    if a.wav:
        with wave.open(a.wav, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(1)
            w.setframerate(a.rate)
            w.writeframes(bytes(((b + 128) & 0xFF) for b in ((x - 256 if x > 127 else x) for x in data[:len(samples)])))
    while len(data) % 4:
        data.append(0)
    name = a.name or os.path.basename(a.out)
    loop = 0 if os.path.basename(a.input).lower().startswith("jingle") else 1
    guard = f"{name.upper()}_H"
    with open(a.out + ".h", "w") as f:
        f.write(f"// Generated by wav2gba.py from {os.path.basename(a.input)} -- do not edit\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(f"#define {name}_len {len(samples)}\n#define {name}_loop {loop}\n#define {name}_rate {a.rate}\n")
        f.write(f"extern const signed char {name}[{len(data)}];\n\n#endif\n")
    with open(a.out + ".c", "w") as f:
        f.write(f"// Generated by wav2gba.py from {os.path.basename(a.input)} -- do not edit\n")
        f.write(f"// {len(samples)} samples at {a.rate} Hz ({len(samples) / a.rate:.1f} s), loop={loop}\n")
        f.write(f"const signed char {name}[{len(data)}] __attribute__((aligned(4))) = {{\n")
        for i in range(0, len(data), 32):
            f.write("".join(f"{b - 256 if b > 127 else b}," for b in data[i:i + 32]) + "\n")
        f.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
