#include "lang.h"

static int current = LANG_FR;

static const char *const strings[LANG_COUNT][STR_COUNT] = {
    [LANG_FR] = {
        [STR_TITLE]       = "DEEPER",
        [STR_PRESS_START] = "APPUYEZ SUR START",
        [STR_CONTINUE]    = "CONTINUER",
        [STR_NEW_RUN]     = "NOUVELLE DESCENTE",
        [STR_DEPTH]       = "PROF.",
        [STR_LIVES]       = "VIES",
        [STR_ORE]         = "MINERAI",
        [STR_HINTS]       = "INDICES",
        [STR_ROOM_DIG]    = "FOUILLES",
        [STR_ROOM_VEIN]   = "FILONS",
        [STR_ROOM_BLOCK]  = "CAVITE",
        [STR_ROOM_TUNNEL] = "GALERIE",
        [STR_ROOM_LEDGER] = "CARNET",
        [STR_ROOM_NUGGET] = "PEPITES",
        [STR_HELP_DIG]    = "1 FOUILLE PAR LIGNE, COLONNE ET ROCHE. JAMAIS COTE A COTE.",
        [STR_HELP_VEIN]   = "AUTANT DE CHAQUE MINERAI PAR LIGNE ET COLONNE, JAMAIS 3 A LA SUITE.",
        [STR_KEY_A_ORE]   = "A MINERAI",
        [STR_KEY_B_ERASE] = "B EFFACER",
        [STR_HELP_LEDGER] = "CHAQUE SYMBOLE UNE FOIS PAR LIGNE, COLONNE ET ZONE.",
        [STR_KEY_A_NEXT]  = "A SUIVANT",
        [STR_KEY_B_PREV]  = "B PRECEDENT",
        [STR_HELP_TUNNEL] = "UNE SEULE GALERIE PAR TOUTES LES CASES, SORTIES DANS L'ORDRE.",
        [STR_KEY_B_BACK]  = "B RECULER",
        [STR_HELP_BLOCK]  = "CHAQUE BLOC UNE FOIS, LA CAVITE REMPLIE SANS TROU. A SUR UN BLOC POSE: REPRENDRE.",
        [STR_KEY_A_PLACE] = "A POSER",
        [STR_KEY_B_NEXT_BLOCK] = "B BLOC SUIV.",
        [STR_KEY_R_TURN]  = "R TOURNER",
        [STR_HELP_NUGGET] = "LES CHIFFRES COMPTENT LES PEPITES VOISINES.",
        [STR_KEY_A_BREAK] = "A CASSER",
        [STR_BIOME_EARTH] = "TERRE",
        [STR_BIOME_ROCK] = "ROCHE",
        [STR_BIOME_ICE] = "GLACE",
        [STR_BIOME_LAVA] = "LAVE",
        [STR_BIOME_CRYSTAL] = "CRISTAL",
        [STR_BIOME_CORE] = "NOYAU",
        [STR_SOUND] = "SON",
        [STR_ON] = "OUI",
        [STR_OFF] = "NON",
        [STR_LANG_PROMPT] = "LANGUE / LANGUAGE",
        [STR_LENGTH_PROMPT] = "LONGUEUR DE LA DESCENTE",
        [STR_LAYERS]      = "PALIERS",
        [STR_LOCKED]      = "VERROUILLE",
        [STR_UNLOCK_LENGTH] = "ATTEINDRE LE NOYAU A",
        [STR_TIME]        = "TEMPS",
        [STR_BEST_TIME]   = "RECORD",
        [STR_LAST_TIME]   = "DERNIER TEMPS",
        [STR_NEW_RECORD]  = "NOUVEAU RECORD!",
        [STR_LENGTH_UNLOCKED] = "DESCENTE PLUS LONGUE DEBLOQUEE!",
        [STR_KEY_A_DIG]   = "A CREUSER",
        [STR_KEY_B_MARK]  = "B MARQUER",
        [STR_KEY_L_HINT]  = "L INDICE",
        [STR_SOLVED]      = "SALLE DEGAGEE!",
        [STR_WRONG_DIG]   = "UNE FOUILLE EST MAL PLACEE",
        [STR_NO_HINTS]    = "PLUS D'INDICES",
        [STR_ORE_FOUND]   = "RECOLTE",
        [STR_NEXT]        = "A CONTINUER",
        [STR_CAMP]        = "CAMPEMENT: REPOS",
        [STR_RISK]        = "RISQUE",
        [STR_STABILITY]   = "STABILITE",
        [STR_COLLAPSE]    = "EBOULEMENT! -1 VIE",
        [STR_ABANDON_ASK] = "ABANDONNER LA SALLE? -1 VIE",
        [STR_YES_NO]      = "A OUI   B NON",
        [STR_CAMP_REST]   = "REPOS AU CAMPEMENT: +1 VIE",
        [STR_MAP_HELP]    = "< > CHOISIR    A DESCENDRE",
        [STR_RUN_WON]     = "LE NOYAU EST ATTEINT!",
        [STR_RUN_LOST]    = "LA DESCENTE S'ARRETE ICI",
        [STR_TOTAL_ORE]   = "MINERAI REMONTE",
        [STR_RECORDS]     = "CARNET DU MINEUR",
        [STR_RUNS]        = "DESCENTES",
        [STR_RUNS_WON]    = "NOYAUX ATTEINTS",
        [STR_BEST_DEPTH]  = "RECORD DE PROF.",
        [STR_POWERS]      = "POUVOIRS",
        [STR_POWER_LAMP]  = "LAMPE: +1 INDICE",
        [STR_POWER_TOUGH] = "ENDURANCE: +1 VIE",
        [STR_POWER_SECOND] = "SECONDE CHANCE",
        [STR_UNLOCK_LAMP] = "ATTEINDRE PROF. 10",
        [STR_UNLOCK_TOUGH] = "ATTEINDRE PROF. 20",
        [STR_UNLOCK_SECOND] = "ATTEINDRE LE NOYAU",
        [STR_NEW_POWER]   = "NOUVEAU POUVOIR!",
        [STR_BACK]        = "B RETOUR",
    },
    [LANG_EN] = {
        [STR_TITLE]       = "DEEPER",
        [STR_PRESS_START] = "PRESS START",
        [STR_CONTINUE]    = "CONTINUE",
        [STR_NEW_RUN]     = "NEW DESCENT",
        [STR_DEPTH]       = "DEPTH",
        [STR_LIVES]       = "LIVES",
        [STR_ORE]         = "ORE",
        [STR_HINTS]       = "HINTS",
        [STR_ROOM_DIG]    = "DIG SITE",
        [STR_ROOM_VEIN]   = "VEINS",
        [STR_ROOM_BLOCK]  = "CAVITY",
        [STR_ROOM_TUNNEL] = "GALLERY",
        [STR_ROOM_LEDGER] = "LEDGER",
        [STR_ROOM_NUGGET] = "NUGGETS",
        [STR_HELP_DIG]    = "1 DIG PER ROW, COLUMN AND ROCK. NEVER TOUCHING.",
        [STR_HELP_VEIN]   = "AS MANY OF EACH ORE PER ROW AND COLUMN, NEVER 3 IN A ROW.",
        [STR_KEY_A_ORE]   = "A ORE",
        [STR_KEY_B_ERASE] = "B ERASE",
        [STR_HELP_LEDGER] = "EACH SYMBOL ONCE PER ROW, COLUMN AND ZONE.",
        [STR_KEY_A_NEXT]  = "A NEXT",
        [STR_KEY_B_PREV]  = "B PREVIOUS",
        [STR_HELP_TUNNEL] = "ONE GALLERY THROUGH EVERY CELL, EXITS IN ORDER.",
        [STR_KEY_B_BACK]  = "B BACK UP",
        [STR_HELP_BLOCK]  = "EVERY BLOCK ONCE, THE CAVITY FILLED WITHOUT GAPS. A ON A PLACED BLOCK: TAKE IT BACK.",
        [STR_KEY_A_PLACE] = "A PLACE",
        [STR_KEY_B_NEXT_BLOCK] = "B NEXT BLOCK",
        [STR_KEY_R_TURN]  = "R TURN",
        [STR_HELP_NUGGET] = "NUMBERS COUNT THE NUGGETS NEXT DOOR.",
        [STR_KEY_A_BREAK] = "A BREAK",
        [STR_BIOME_EARTH] = "EARTH",
        [STR_BIOME_ROCK] = "ROCK",
        [STR_BIOME_ICE] = "ICE",
        [STR_BIOME_LAVA] = "LAVA",
        [STR_BIOME_CRYSTAL] = "CRYSTAL",
        [STR_BIOME_CORE] = "CORE",
        [STR_SOUND] = "SOUND",
        [STR_ON] = "ON",
        [STR_OFF] = "OFF",
        [STR_LANG_PROMPT] = "LANGUE / LANGUAGE",
        [STR_LENGTH_PROMPT] = "LENGTH OF THE DESCENT",
        [STR_LAYERS]      = "LAYERS",
        [STR_LOCKED]      = "LOCKED",
        [STR_UNLOCK_LENGTH] = "REACH THE CORE AT",
        [STR_TIME]        = "TIME",
        [STR_BEST_TIME]   = "BEST",
        [STR_LAST_TIME]   = "LAST TIME",
        [STR_NEW_RECORD]  = "NEW RECORD!",
        [STR_LENGTH_UNLOCKED] = "LONGER DESCENT UNLOCKED!",
        [STR_KEY_A_DIG]   = "A DIG",
        [STR_KEY_B_MARK]  = "B MARK",
        [STR_KEY_L_HINT]  = "L HINT",
        [STR_SOLVED]      = "ROOM CLEARED!",
        [STR_WRONG_DIG]   = "A DIG IS MISPLACED",
        [STR_NO_HINTS]    = "NO HINTS LEFT",
        [STR_ORE_FOUND]   = "HAUL",
        [STR_NEXT]        = "A CONTINUE",
        [STR_CAMP]        = "CAMP: REST",
        [STR_RISK]        = "RISK",
        [STR_STABILITY]   = "STABILITY",
        [STR_COLLAPSE]    = "CAVE-IN! -1 LIFE",
        [STR_ABANDON_ASK] = "LEAVE THE ROOM? -1 LIFE",
        [STR_YES_NO]      = "A YES   B NO",
        [STR_CAMP_REST]   = "REST AT THE CAMP: +1 LIFE",
        [STR_MAP_HELP]    = "< > CHOOSE    A DESCEND",
        [STR_RUN_WON]     = "THE CORE IS REACHED!",
        [STR_RUN_LOST]    = "THE DESCENT ENDS HERE",
        [STR_TOTAL_ORE]   = "ORE BROUGHT BACK",
        [STR_RECORDS]     = "MINER'S LOGBOOK",
        [STR_RUNS]        = "DESCENTS",
        [STR_RUNS_WON]    = "CORES REACHED",
        [STR_BEST_DEPTH]  = "DEPTH RECORD",
        [STR_POWERS]      = "POWERS",
        [STR_POWER_LAMP]  = "LAMP: +1 HINT",
        [STR_POWER_TOUGH] = "STAMINA: +1 LIFE",
        [STR_POWER_SECOND] = "SECOND CHANCE",
        [STR_UNLOCK_LAMP] = "REACH DEPTH 10",
        [STR_UNLOCK_TOUGH] = "REACH DEPTH 20",
        [STR_UNLOCK_SECOND] = "REACH THE CORE",
        [STR_NEW_POWER]   = "NEW POWER!",
        [STR_BACK]        = "B BACK",
    },
};

void lang_set(int lang) { current = clampi(lang, 0, LANG_COUNT - 1); }

const char *lang_name(int lang)
{
    static const char *const names[LANG_COUNT] = { "FRANCAIS", "ENGLISH" };
    return names[clampi(lang, 0, LANG_COUNT - 1)];
}
int  lang_get(void) { return current; }

const char *S(int id)
{
    if (id < 0 || id >= STR_COUNT) return "";
    const char *s = strings[current][id];
    return s ? s : strings[LANG_EN][id];
}
